// =============================================================================
// 📁 src/components/icons/categories/communication.ts
export {
    Chat,
    ChatCircle,
    ChatTeardrop,
    Envelope,
    EnvelopeOpen,
    EnvelopeSimple,
    Phone,
    PhoneCall,
    PhoneIncoming,
    PhoneOutgoing,
    Bell,
    BellRinging,
    BellSlash,
    Megaphone,
    MegaphoneSimple,
    Microphone,
    MicrophoneSlash,
    Video,
    VideoCamera,
    VideoCameraSlash,
    Share,
    ShareNetwork,
    Export,
    PaperPlane,
    PaperPlaneRight,
} from '@phosphor-icons/react';