// =============================================================================
// 📁 src/components/icons/categories/media.ts
export {
    Play,
    PlayCircle,
    Pause,
    PauseCircle,
    Stop,
    StopCircle,
    SkipBack,
    SkipBackCircle,
    SkipForward,
    SkipForwardCircle,
    FastForward,
    FastForwardCircle,
    Rewind,
    RewindCircle,
    Repeat,
    RepeatOnce,
    Shuffle,
    ShuffleSimple,
    SpeakerHigh,
    SpeakerLow,
    SpeakerNone,
    SpeakerSlash,
    SpeakerX,
    MusicNote,
    MusicNotes,
    MusicNoteSimple,
    Image,
    Images,
    Camera,
    CameraPlus,
    CameraSlash,
    FilmReel,
    FilmStrip,
    Palette,
} from '@phosphor-icons/react';