// =============================================================================
// 📁 src/components/icons/categories/navigation.ts
export {
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowDown,
    ArrowCircleLeft,
    ArrowCircleRight,
    ArrowCircleUp,
    ArrowCircleDown,
    CaretLeft,
    CaretRight,
    CaretUp,
    CaretDown,
    CaretDoubleLeft,
    CaretDoubleRight,
    CaretDoubleUp,
    CaretDoubleDown,
    House,
    HouseSimple,
    List,
    SquaresFour,
    Sidebar,
    SidebarSimple,
    NavigationArrow,
    Compass,
    MapPin,
    Path,
} from '@phosphor-icons/react';