// =============================================================================
// 📁 src/components/icons/categories/social.ts
export {
    FacebookLogo,
    TwitterLogo,
    InstagramLogo,
    LinkedinLogo,
    GithubLogo,
    GoogleLogo,
    AppleLogo,
    MicrosoftOutlookLogo,
    MicrosoftTeamsLogo,
    SlackLogo,
    DiscordLogo,
    TelegramLogo,
    WhatsappLogo,
    SnapchatLogo,
    TiktokLogo,
    YoutubeLogo,
    SpotifyLogo,
    TwitchLogo,
    RedditLogo,
    PinterestLogo,
    BehanceLogo,
    DribbbleLogo,
    FigmaLogo,
    NotionLogo,
    SketchLogo,
    FediverseLogo,
    MastodonLogo,
    ThreadsLogo,
} from '@phosphor-icons/react';
